config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root 'users#show'
  root 'brogs#index'
  resources :brogs do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/brog.rb
class Brog < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :brog               #tweetsテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :brogs
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/brogs_controller.rb
class BrogsController < ApplicationController
  #before_action :move_to_index, except: :index
  before_action :move_to_index, :except => [:index,:show]
  def index
    #@brogs = Brog.order("created_at DESC").page(params[:page]).per(5)
     @brogs = Brog.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @brog = Brog.new
  end

  def create
      #Brog.create(brog_params)
      Brog.create(title: brog_params[:title], text: brog_params[:text], user_id: current_user.id)
  end
  def destroy
      brog = Brog.find(params[:id])
      brog.destroy if brog.user_id == current_user.id
  end
  def edit
      @brog = Brog.find(params[:id])
  end
  def update
      brog = Brog.find(params[:id])
      brog.update(brog_params) if brog.user_id == current_user.id
  end
   def show
    @brog = Brog.find(params[:id])
    @comments = @brog.comments.includes(:user)
  end

    private
    def brog_params
      params.require(:brog).permit(:title, :text)
    end
    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], brog_id: comment_params[:brog_id], user_id: current_user.id)
    redirect_to "/brogs/#{@comment.brog.id}"   #コメントと結びつくツイートの詳細画面に遷移する
  end
  private
  def comment_params
    params.permit(:text, :brog_id)
  end
end

app/controllers/matelpage_controller.rb
class MatelpageController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @brogs = user.brogs.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brogs_helper.rb
module BrogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/matelpage_helper.rb
module MatelpageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brogs/_brog.html.erb
<div class="content_post">




<div class=rectangle>
  <div class="row">
    <div class="col s12 m5">
      <div class="card-panel white">
        <span class="black-text"><%= brog.title %>
        </span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m12">
      <div class="card-panel blue-grey darken-1">
        <span class="white-text"><%= brog.text %>

        </span>
      </div>
    </div>
  </div>

<span class="name">
    <a href="/users/<%= brog.user_id %>">
      <span>投稿者</span><%= brog.user.nickname %>
    </a>
  </span>>
</div>
</div>

<%= link_to "詳細", brog_path(brog.id), method: :get , class: 'waves-effect waves-light btn'%>




<% if user_signed_in? && current_user.id == brog.user_id %>

        <%= link_to '編集', "/brogs/#{brog.id}/edit", method: :get, class: 'waves-effect waves-light btn'%>

        <%= link_to '削除', "/brogs/#{brog.id}", method: :delete, data: { confirm: '削除しますか？' }  , class: 'waves-effect waves-light btn'%>
 <% end %>

app/views/brogs/create.html.erb
 <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/brogs">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/brogs/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/brogs/edit.html.erb
<div class="contents row">


    <%= form_for @brog do |f| %>
      <%= f.text_field :title,style: 'width: 80%;height: 50px;' %>


      <div style="margin: 8px 0">
            <%= f.text_area :text, style: 'width: 100%;height: 300px;' %>
          </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
</div>

app/views/brogs/index.html.erb
<div class="contents row">
  <% @brogs.each do |brog| %>
    <%= render partial: "brog", locals: { brog: brog } %>
  <% end %>
  <%= paginate(@brogs) %>
</div>

app/views/brogs/new.html.erb
<div class="contents row">
   <div class="container">

    <%= form_for @brog do |f| %>
      <%= f.text_field :title, placeholder: 'title',style: 'width: 80%;height: 50px;' %>


      <div style="margin: 8px 0">
            <%= f.text_area :text, placeholder: 'ブログを書いてね！', style: 'width: 100%;height: 300px;' %>
          </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
    </div>
</div>

app/views/brogs/new.htmlのコピー.erb
<div class="contents row">
   <div class="container">
  <%= form_tag('/brogs', method: :post) do %>
    <h5>
      投稿する
    </h5>
    <input placeholder="title" type="string" name="title" autofocus="true">
    <textarea placeholder="text" name="text" cols="30" rows="10"></textarea>
    <input type="submit" value="SENT">

   <% end %>

    </div>
</div>

app/views/brogs/show.html.erb
<div class ="contents row">
  <div class="content_post">
    <% if user_signed_in? && current_user.id == @brog.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/brogs/#{@brog.id}/edit", method: :get, class: 'waves-effect waves-light btn'%>
        </li>
        <li>
          <%= link_to '削除', "/brogs/#{@brog.id}", method: :delete, data: { confirm: '削除しますか？' }  , class: 'waves-effect waves-light btn'%>
        </li>
      </ul>
    </div>
    <% end %>

<div class="row">
    <div class="col s12 m5">
      <div class="card-panel blue-grey darken-1">
        <span class="white-text"><%= @brog.title %>
        </span>
      </div>
    </div>
  </div>

   <div class="row">
    <div class="col s12 m12">
      <div class="card-panel blue-grey darken-1">
        <span class="white-text"><%= @brog.text %>

        </span>
      </div>
    </div>
  </div>

    <span class="name">
      <a href="/users/<%= @brog.user.id %>">
        <span>投稿者</span><%= @brog.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <!-- ここからフォーム -->
    <% if current_user %>
      <%= form_tag("/brogs/#{@brog.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
    <!-- ここから追記してください -->
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/brogs/show.htmlのコピー.erb
<div class ="contents row">
  <div class="content_post">
    <% if user_signed_in? && current_user.id == @brog.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/brogs/#{@brog.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/brogs/#{@brog.id}", method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <%= simple_format(@brog.text) %>
    <span class="name">
      <a href="/users/<%= @brog.user.id %>">
        <span>投稿者</span><%= @brog.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <!-- ここからフォーム -->
    <% if current_user %>
      <%= form_tag("/brogs/#{@brog.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
    <!-- ここから追記してください -->
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/brogs/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
<script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>


<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.1/css/materialize.min.css' />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.1/js/materialize.min.js'></script>



     <title>miniblog</title>
  <style type="text/css" href="./style.css"></style>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script   src="https://code.jquery.com/jquery-3.3.1.js"   integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="   crossorigin="anonymous"></script>
  </head>

 <body>
   <nav class="blue-grey darken-1">
  <div class="nav-wrapper">
    <a href="http://localhost:3000/" class="brand-logo">Enjoy Blog！</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">



        <% if user_signed_in? %>

          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>


         <div class="waves-effect waves-light btn">
           <a class="post" href="/brogs/new">投稿</a>
         </div>

        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
        </div>
      <% end %>
      </div>



   </ul>
  </div>
</nav>

    <%= yield %>

    <footer>
      <p>
        ""
      </p>
    </footer>
  </body>
</html>

app/views/layouts/application.htmlのコピー.erb
<!DOCTYPE html>
<html>
  <head>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
<script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>


  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.1/css/materialize.min.css' />
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.1/js/materialize.min.js'></script>

     <title>miniapp</title>
  <style type="text/css" href="./style.css"></style>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script   src="https://code.jquery.com/jquery-3.3.1.js"   integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="   crossorigin="anonymous"></script>
  </head>

 <body>
   <nav class="blue-grey darken-1">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">Brog</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">

        <% if user_signed_in? %>

          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <a class="post" href="/brogs/new">投稿</a>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
        </div>
      <% end %>
      </div>

   </ul>
  </div>
</nav>

    <%= yield %>

    <footer>
      <p>
        ""
      </p>
    </footer>
  </body>
</html>

app/views/layouts/copy_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>miniBrog</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">EnjoyBrog!</a></h1>
        <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <a class="post" href="/brogs/new">投稿する</a>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
          <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
        </div>
      <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright MiniBrog 2018.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
 <div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @brogs.each do |brog| %>
    <%= render partial: "brogs/brog", locals: { brog: brog } %>
  <% end %>
  <%= paginate(@brogs) %>
</div>

app/views/users/show.htmlのコピー.erb
 <div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @brogs.each do |brog| %>
      <div class="content_post">
        <textarea cols="20" name="title" placeholder="strig" rows="1"><%= brog.title %></textarea>
        <br>
        <br>
      <textarea cols="60" name="text" placeholder="text" rows="10"><%= brog.text %></textarea>
      </div>
    <% end %>
    <%= paginate(@brogs) %>
  </div>